# Generated by Django 5.1 on 2024-08-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omidpaytoken',
            old_name='reserve_number',
            new_name='user_id',
        ),
    ]
